### ISSUE TITLE
Integrate MockEnvironment into PHPUnit - notably call disable() automatically

### ISSUE THREAD

**Issue by malkusch** [malkusch/php-mock#7]
There should be a way to have `MockEnvironment::disable()` called automatically after a PHPUnit test. This issue is inspired by #6.

I feel like adding the method `PHPMock::registerForTearDown()` which would accept `Mock` and `MockEnvironment` (which both would share a common interface).

**Comment by geoffroy-aubry** [comment]
:+1:
